#!/bin/sh

# UNTESTED - IN DEVELOPMENT

# Sar runner/monitor
# 
# Keeps sar running while ensuring its resource usage is kept under control
#
# Start this from inittab or call every minute from cron

# --- CONFIGURATION  ---
CONFIG_FILE=/etc/sysconfig/sadc
SAMPLE_INTERVAL=60  # collect data every N seconds
MAX_RUNTIME=0	    # After N minutes, restart sadc 
SADC_OPTS="-S XALL"
SADC=/usr/lib64/sa/sadc

# --- end configuration ---

PATH=/usr/sbin:/sbin:usr/bin:/bin
export PATH

write_pid() { 
  if ( set -o noclobber; echo $$ > "$1" ) 2>/dev/null; then
    trap 'rm -f "$1"; pkill sadc; exit 0' INT TERM EXIT
    return 0
  else
    return 1
  fi
}

exclusive_mode() { 
  pidf=/var/run/sadc.pid
  if ! write_pid $pidf; then
    read pid < "$pidf"
    if ps -j -p $pid | awk 'NR==2 {print $6}'|grep -qF "${0##*/}" ; then
      exit 0
    else
      rm "$pidf" && write_pid || exit 1
    fi
  fi
}
exclusive_mode

source "$CONFIG_FILE"

echo -15 >/proc/$$/oom_adj
pkill sadc
while true; do 
  sec_to_midnight=$(( $( date -d 23:59:59 +%s ) - $( date +%s ) ))

  if [[ $MAX_RUNTIME = 0 -o $MAX_RUNTIME -gt $sec_to_midnight ]]; then
    MAX_RUNTIME=$sec_to_midnight
  fi

  if [[ $MAX_RUNTIME -lt $SAMPLE_INTERVAL ]]; then
    count=1
  else
    count=$(( MAX_RUNTIME / SAMPLE_INTERVAL + 1 ))
  fi

  timeout $MAX_RUNTIME $SADC -L -F $SADC_OPTS $SAMPLE_INTERVAL $count - 
done
